services:
  gameset:
    container_name: gameset
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      DATABASE_URI: "jdbc:postgresql://database:5432/${PG_NAME}?user=${PG_USER}&password=${PG_PASSWORD}"
    ports:
      - "${BIND_IP}:${BIND_PORT}:9000"
    volumes:
      - ./data/gameset:/opt/gameset/data
  db:
    container_name: database
    image: postgres:15.0-bullseye
    restart: always
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
